# Generated by Django 5.0.6 on 2024-07-18 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
