# Generated by Django 5.0.6 on 2024-07-21 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='starts',
            new_name='stars',
        ),
    ]
